Features & Issues

* Generate more numbers as the document IDs (this makes it easier to
   manipulate the URL since the ID is treated as a single word)

* Change "add description" to "change description" when it already exists

* Make sure the "add/change description" buttons are there both on page load
   and when we add the description later.

* Make the lists pretty
* Add list deletion
* Undo for deletion


* Have a look whether it makes more sense to abandon jQuery UI entirely and use
   jQuery's Drag & Drop functionality directly for listSortable.

* Add filtering by document type into the Documara API
  - e.g. GET /api/documents?type=lists
  - Expect "type=text" when no type provided
  - Return all documents of all types on "type=all"

* speed up the document search

* speed up the document-index loading time
   If the client supports localStorage, we can use it to store the list of
   documents and just load the new stuff.

   The client already keeps track of the timestamp of the last modification of
   any document (the first one in the list). We can add a `since=timestamp`
   query parameter to the /api/documents/ call and return just docs modified
   after that.

   Redis' command `ZRANGEBYSCORE` allows us to do that for the sorted sets.

* Change the colour theme
   The background and foreground colours were taken from notepad.cc because it
   was quick and I wanted something that looks good for my prototyping and
   testing.

   This must be replaced with a colour theme that I have undisputable right to
   use and distribute.

* Add Offline mode

* Allow document deletion
