* Features & Issues
** it should be able to add a new document using the "Search docs" textbox
    when the user types something to the box, we'll insert a "Create new
    document" entry into the documents index and highlight it.

    Pressing enter would create a new doc with the entered text as the title.

    Pressing down arrow key would allow the user to navigate and select existing
    documents.
** speed up the document-index loading time
   If the client supports localStorage, we can use it to store the list of
   documents and just load the new stuff.

   The client already keeps track of the timestamp of the last modification of
   any document (the first one in the list). We can add a `since=timestamp`
   query parameter to the /api/documents/ call and return just docs modified
   after that.

   Redis' command `ZRANGEBYSCORE` allows us to do that for the sorted sets.
** Change the colour theme
   The background and foreground colours were taken from notepad.cc because it
   was quick and I wanted something that looks good for my prototyping and
   testing.

   This must be replaced with a colour theme that I have undisputable right to
   use and distribute.
** Add Offline mode
** Allow document deletion
