* Features & Issues
** Firefox compatibility
*** keyboard selection not very visible on document-index page
    Regardless of the browser/OS focus cues, we should highlight the item same
    way as we do when we hover over it with the mouse.
** missing user-info area on the document-show page
** it should be able to add a new document using the "Search docs" textbox
    when the user types something to the box, we'll insert a "Create new
    document" entry into the documents index and highlight it.

    Pressing enter would create a new doc with the entered text as the title.

    Pressing down arrow key would allow the user to navigate and select existing
    documents.
** Dead mouse hover space between document items in the index page
   When the user moves mouse in-between two document items, none is highlighted.

   To satisfy mister Fitts, we should dedicate the space to the menu items as
   well even if we keep the visuals as they are. There's no reason to deselect
   the items as long as we're within the <ul> element.
** Search box misaligned with the Documents box on the index page
** the user-info area should show the user's name/email
** speed up the document-index loading time
   If the client supports localStorage, we can use it to store the list of
   documents and just load the new stuff.

   The client already keeps track of the timestamp of the last modification of
   any document (the first one in the list). We can add a `since=timestamp`
   query parameter to the /api/documents/ call and return just docs modified
   after that.

   Redis' command `ZRANGEBYSCORE` allows us to do that for the sorted sets.
** Change the colour theme
   The background and foreground colours were taken from notepad.cc because it
   was quick and I wanted something that looks good for my prototyping and
   testing.

   This must be replaced with a colour theme that I have undisputable right to
   use and distribute.
** Add Offline mode
** Allow document deletion
