Features & Issues

* Change "add description" to "change description" when it already exists

* Add list deletion

* Undo for list and item deletion

* Prevent the flash of unstyled content

* Have a look whether it makes more sense to abandon jQuery UI entirely and use
   jQuery's Drag & Drop functionality directly for listSortable.

* speed up the document search

* speed up the document-index loading time
   If the client supports localStorage, we can use it to store the list of
   documents and just load the new stuff.

   The client already keeps track of the timestamp of the last modification of
   any document (the first one in the list). We can add a `since=timestamp`
   query parameter to the /api/documents/ call and return just docs modified
   after that.

   Redis' command `ZRANGEBYSCORE` allows us to do that for the sorted sets.

* Change the colour theme
   The background and foreground colours were taken from notepad.cc because it
   was quick and I wanted something that looks good for my prototyping and
   testing.

   This must be replaced with a colour theme that I have undisputable right to
   use and distribute.

* Switch between pages without the full page reload

* Add Offline mode

* Allow document deletion
